// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfu3JX4OImvu83AWJxgfq9VIgV64WT_eg',
    appId: '1:621674846439:web:bdebc04dfcec4f30466a42',
    messagingSenderId: '621674846439',
    projectId: 'help-elder-38d24',
    authDomain: 'help-elder-38d24.firebaseapp.com',
    databaseURL: 'https://help-elder-38d24-default-rtdb.firebaseio.com',
    storageBucket: 'help-elder-38d24.appspot.com',
    measurementId: 'G-JBLBC1R4XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9yjA3nft8KxHSu4LHkSTDxn-N4RhJjlo',
    appId: '1:621674846439:android:35bac5cffba55dfd466a42',
    messagingSenderId: '621674846439',
    projectId: 'help-elder-38d24',
    databaseURL: 'https://help-elder-38d24-default-rtdb.firebaseio.com',
    storageBucket: 'help-elder-38d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpsscxx2hOcriusbA9Ih_qinzYy-gx1NQ',
    appId: '1:621674846439:ios:64449f6de9c41fe5466a42',
    messagingSenderId: '621674846439',
    projectId: 'help-elder-38d24',
    databaseURL: 'https://help-elder-38d24-default-rtdb.firebaseio.com',
    storageBucket: 'help-elder-38d24.appspot.com',
    iosClientId: '621674846439-eu68f4l3uk2vmutc8a9ckiu1toc5ap6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpElder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpsscxx2hOcriusbA9Ih_qinzYy-gx1NQ',
    appId: '1:621674846439:ios:64449f6de9c41fe5466a42',
    messagingSenderId: '621674846439',
    projectId: 'help-elder-38d24',
    databaseURL: 'https://help-elder-38d24-default-rtdb.firebaseio.com',
    storageBucket: 'help-elder-38d24.appspot.com',
    iosClientId: '621674846439-eu68f4l3uk2vmutc8a9ckiu1toc5ap6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.helpElder',
  );
}
